### ISSUE TITLE
version without dependencies

### ISSUE THREAD

**Issue by fitnr** [defunctzombie/typeahead#12]
I've forked typeahead and edited it to remove the dependencies. This changes the API a little - `options.menu` and `options.item` must now be passed as tag names, as opposed to HTML strings, e.g.:

``` javascript
new Typeahead(input, {
    menu: 'div',
    item: 'span'
});
```

Additionally, I changed the match handler a bit in order to accept objects as matches (as long as they have a `value` key). The other keys are added to the match item's dataset, then copied to the input upon selection. This makes then available for the event handler. For instance, the matches might be locations; the name is shown on screen, and the lat/long can be handled upon select:

``` javascript
new Typeahead(input, {
    source: function(query, callback) {
       callback([
         {value: 'some city', lat: 42, lng: -72},
         {value: 'some other', lat: -42, lng: 84}
       ])
   }
});
```

I also found that the `change` event wasn't working, it fires even when a final selection hasn't been made, so I've namespaced it to `change.typeahead`.

Would you be interested in a pull with these changes?

**Comment by defunctzombie** [comment]
Any particular reason to remove the dependencies? I see no real benefit to doing so but if you have a compelling argument maybe.

**Comment by fitnr** [comment]
- simplifies things for novice developers, as one can just include the dist file, rather than running it through browserify (or a similar bundler)
- It reduces the size of the final product quite a bit. It's not a large package, but every little byte helps.
- using Vanilla JS is faster. Again, not a huge concern, but means the library will work better on a page with heavy JS.

No big deal if this isn't what you're looking for, though. I can make a pull with just the renamed event or support for objects, if you're interested in either of those changes.

**Comment by defunctzombie** [comment]
Honestly I don't maintain this module much anymore. I don't find much value in bullet point 1 since there are web based CDN tools for this and in general more and more requires modules.

For points 2 and 3 I could be swayed. Maybe open the PR and we can see what the diff looks like.

I will caution that I don't have much time that I spend on these web components these days so responses are not speedy.

**Comment by fitnr** [comment]
See #13
